const opTypes = {
  0: "Transfer",
  1: "Limit order create",
  2: "Limit order cancel",
  3: "Call order update",
  4: "Limit order filled",
  5: "Account creation",
  6: "Account update",
  7: "Account whitelist",
  8: "Account upgrade",
  9: "Account transfer",
  10: "Asset create",
  11: "Asset update",
  12: "Asset update bitasset",
  13: "Asset update feed producers",
  14: "Asset issue",
  15: "Asset reserve",
  16: "Asset fund fee pool",
  17: "Asset settle",
  18: "Asset global settle",
  19: "Asset publish feed",
  20: "Witness create",
  21: "Witness update",
  22: "Proposal create",
  23: "Proposal update",
  24: "Proposal delete",
  25: "Withdraw permission create",
  26: "Withdraw permission update",
  27: "Withdraw permission claim",
  28: "Withdraw permission delete",
  29: "Committee member create",
  30: "Committee member update",
  31: "Committee member update global parameters",
  32: "Vesting balance create",
  33: "Vesting balance withdraw",
  34: "Worker create",
  35: "Custom operation",
  36: "Assert",
  37: "Balance claim",
  38: "Override transfer",
  39: "Transfer to blind",
  40: "Blind transfer",
  41: "Transfer from blind",
  42: "Asset settle cancel",
  43: "Asset claim fees",
  44: "FBA distribute",
  45: "Collateral bid",
  46: "Execute bid",
  47: "Asset claim pool",
  48: "Asset update issuer",
  49: "HTLC create",
  50: "HTLC redeem",
  51: "HTLC redeemed",
  52: "HTLC extend",
  53: "HTLC refund",
  54: "Custom authority create",
  55: "Custom authority update",
  56: "Custom authority delete",
  57: "Ticket create",
  58: "Ticket update",
  59: "Create liquidity pool",
  60: "Delete liquidity pool",
  61: "Liquidity pool deposit",
  62: "Liquidity pool withdraw",
  63: "Liquidity pool exchange",
  64: "SameT fund create",
  65: "SameT fund delete",
  66: "SameT fund update",
  67: "SameT fund borrow",
  68: "SameT fund repay",
  69: "Create credit offer",
  70: "Delete credit offer",
  71: "Update credit offer",
  72: "Accept credit offer",
  73: "Repay credit deal",
  74: "Credit deal expired",
  75: "Update liquidity pool",
  76: "Update credit deal",
  77: "Update limit order",
};

const operationTypes = [
  {
    id: 0,
    from: "",
    method: "transfer",
  },
  {
    id: 1,
    from: "seller",
    method: "limit_order_create",
  },
  {
    id: 2,
    from: "fee_paying_account",
    method: "limit_order_cancel",
  },
  {
    id: 3,
    from: "funding_account",
    method: "call_order_update",
  },
  {
    id: 5,
    from: "registrar",
    method: "account_create",
  },
  {
    id: 6,
    from: "account",
    method: "account_update",
  },
  {
    id: 7,
    from: "authorizing_account",
    method: "account_whitelist",
  },
  {
    id: 8,
    from: "account_to_upgrade",
    method: "account_upgrade",
  },
  {
    id: 9,
    from: "account_id",
    method: "account_transfer",
  },
  {
    id: 10,
    from: "issuer",
    method: "asset_create",
  },
  {
    id: 11,
    from: "issuer",
    method: "asset_update",
  },
  {
    id: 12,
    from: "issuer",
    method: "asset_update_bitasset",
  },
  {
    id: 13,
    from: "issuer",
    method: "asset_update_feed_producers",
  },
  {
    id: 14,
    from: "issuer",
    method: "asset_issue",
  },
  {
    id: 15,
    from: "payer",
    method: "asset_reserve",
  },
  {
    id: 16,
    from: "from_account",
    method: "asset_fund_fee_pool",
  },
  {
    id: 17,
    from: "account",
    method: "asset_settle",
  },
  {
    id: 18,
    from: "issuer",
    method: "asset_global_settle",
  },
  {
    id: 19,
    from: "publisher",
    method: "asset_publish_feed",
  },
  {
    id: 20,
    from: "witness_account",
    method: "witness_create",
  },
  {
    id: 21,
    from: "witness_account",
    method: "witness_update",
  },
  {
    id: 22,
    from: "fee_paying_account",
    method: "proposal_create",
  },
  {
    id: 23,
    from: "fee_paying_account",
    method: "proposal_update",
  },
  {
    id: 24,
    from: "fee_paying_account",
    method: "proposal_delete",
  },
  {
    id: 25,
    from: "withdraw_from_account",
    method: "withdraw_permission_create",
  },
  {
    id: 26,
    from: "withdraw_from_account",
    method: "withdraw_permission_update",
  },
  {
    id: 27,
    from: "withdraw_from_account",
    method: "withdraw_permission_claim",
  },
  {
    id: 28,
    from: "withdraw_from_account",
    method: "withdraw_permission_delete",
  },
  {
    id: 29,
    from: "committee_member_account",
    method: "committee_member_create",
  },
  {
    id: 30,
    from: "",
    method: "committee_member_update",
  },
  {
    id: 31,
    from: "committee_member_account",
    method: "committee_member_update_global_parameters",
  },
  {
    id: 32,
    from: "",
    method: "vesting_balance_create",
  },
  {
    id: 33,
    from: "owner",
    method: "vesting_balance_withdraw",
  },
  {
    id: 34,
    from: "owner",
    method: "worker_create",
  },
  {
    id: 35,
    from: "payer",
    method: "custom",
  },
  {
    id: 36,
    from: "fee_paying_account",
    method: "assert",
  },
  {
    id: 37,
    from: "deposit_to_account",
    method: "balance_claim",
  },
  {
    id: 38,
    from: "from",
    method: "override_transfer",
  },
  {
    id: 39,
    from: "from",
    method: "transfer_to_blind",
  },
  {
    id: 40,
    from: "",
    method: "blind_transfer",
  },
  {
    id: 41,
    from: "",
    method: "transfer_from_blind",
  },
  {
    id: 43,
    from: "issuer",
    method: "asset_claim_fees",
  },
  {
    id: 45,
    from: "bidder",
    method: "bid_collateral",
  },
  {
    id: 47,
    from: "issuer",
    method: "asset_claim_pool",
  },
  {
    id: 48,
    from: "issuer",
    method: "asset_update_issuer",
  },
  {
    id: 49,
    from: "from",
    method: "htlc_create",
  },
  {
    id: 50,
    from: "redeemer",
    method: "htlc_redeem",
  },
  {
    id: 52,
    from: "update_issuer",
    method: "htlc_extend",
  },
  {
    id: 54,
    from: "account",
    method: "custom_authority_create",
  },
  {
    id: 55,
    from: "account",
    method: "custom_authority_update",
  },
  {
    id: 56,
    from: "account",
    method: "custom_authority_delete",
  },
  {
    id: 57,
    from: "account",
    method: "ticket_create",
  },
  {
    id: 58,
    from: "account",
    method: "ticket_update",
  },
  {
    id: 59,
    from: "account",
    method: "liquidity_pool_create",
  },
  {
    id: 60,
    from: "account",
    method: "liquidity_pool_delete",
  },
  {
    id: 61,
    from: "account",
    method: "liquidity_pool_deposit",
  },
  {
    id: 62,
    from: "account",
    method: "liquidity_pool_withdraw",
  },
  {
    id: 63,
    from: "account",
    method: "liquidity_pool_exchange",
  },
  {
    id: 64,
    from: "owner_account",
    method: "samet_fund_create",
  },
  {
    id: 65,
    from: "owner_account",
    method: "samet_fund_delete",
  },
  {
    id: 66,
    from: "owner_account",
    method: "samet_fund_update",
  },
  {
    id: 67,
    from: "borrower",
    method: "samet_fund_borrow",
  },
  {
    id: 68,
    from: "account",
    method: "samt_fund_repay",
  },
  {
    id: 69,
    from: "owner_account",
    method: "credit_offer_create",
  },
  {
    id: 70,
    from: "owner_account",
    method: "credit_offer_delete",
  },
  {
    id: 71,
    from: "owner_account",
    method: "credit_offer_update",
  },
  {
    id: 72,
    from: "borrower",
    method: "credit_offer_accept",
  },
  {
    id: 73,
    from: "account",
    method: "credit_deal_repay",
  },
  {
    id: 75,
    from: "account",
    method: "liquidity_pool_update_operation",
  },
  {
    id: 76,
    from: "account",
    method: "credit_deal_update_operation",
  },
  {
    id: 77,
    from: "seller",
    method: "limit_order_update_operation",
  },
];

export { opTypes, operationTypes };
