// Canonical list of themable pages. `slug` must match the `page` prop passed
// to <PageHeader /> on each Astro page (that value is what PageHeader publishes
// to $currentPage and what per-page theme overrides are keyed by).
export const THEMABLE_PAGES = [
  { slug: "index", label: "Home" },
  { slug: "dex", label: "DEX" },
  { slug: "instant_trade", label: "Instant Trade" },
  { slug: "pool", label: "Swap" },
  { slug: "stake", label: "Stake" },
  { slug: "transfer", label: "Transfer" },
  { slug: "timed_transfer", label: "Timed Transfer" },
  { slug: "withdraw_permissions", label: "Withdraw Permissions" },
  { slug: "htlc", label: "HTLC" },
  { slug: "create_vesting", label: "Create Vesting" },
  { slug: "borrow", label: "Borrow" },
  { slug: "offereditor", label: "Lend" },
  { slug: "smartcoins", label: "Smartcoins" },
  { slug: "smartcoin", label: "Smartcoin" },
  { slug: "tfunds", label: "TradeFunds" },
  { slug: "tfund_user", label: "TradeFund (user)" },
  { slug: "settlement", label: "Settlement" },
  { slug: "uia", label: "Create UIA" },
  { slug: "create_smartcoin", label: "Create Smartcoin" },
  { slug: "create_pool", label: "Create Pool" },
  { slug: "portfolio-balances", label: "Balances" },
  { slug: "portfolio-open-orders", label: "Open Orders" },
  { slug: "portfolio-recent-activity", label: "Recent Activity" },
  { slug: "issuedAssets", label: "Issued Assets" },
  { slug: "AccountLists", label: "Account Lists" },
  { slug: "blocked-users", label: "Blocked Users" },
  { slug: "barter", label: "Barter" },
  { slug: "favourites", label: "Favourites" },
  { slug: "offers", label: "Offers" },
  { slug: "offer", label: "Offer" },
  { slug: "order", label: "Order" },
  { slug: "deals", label: "Deals" },
  { slug: "vesting", label: "Vesting" },
  { slug: "proposals", label: "Proposals" },
  { slug: "blocks", label: "Blocks" },
  { slug: "custom_pool_overview", label: "Custom Pool Overview" },
  { slug: "custom_pool_tracker", label: "Custom Pool Tracker" },
  { slug: "pools", label: "Pools" },
  { slug: "vote", label: "Vote" },
  { slug: "witnesses", label: "Witnesses" },
  { slug: "committee", label: "Committee" },
  { slug: "committee_parameters", label: "Committee Parameters" },
  { slug: "governance", label: "Governance" },
  { slug: "create_worker", label: "Create Worker" },
  { slug: "ticket_leaderboard", label: "Ticket Leaderboard" },
  { slug: "create_ticket", label: "Create Ticket" },
  { slug: "invoice_inventory", label: "Invoice Inventory" },
  { slug: "create_invoice", label: "Create Invoice" },
  { slug: "pay_invoice", label: "Pay Invoice" },
  { slug: "stored_invoices", label: "Stored Invoices" },
  { slug: "nodes", label: "Nodes" },
  { slug: "ltm", label: "Lifetime Membership" },
  { slug: "create_account", label: "Create Account" },
  { slug: "change_password", label: "Change Password" },
  { slug: "featured", label: "Featured" },
  { slug: "configure_visuals", label: "Configure Visuals" },
  { slug: "theme_customizer", label: "Theme Customization" },
  { slug: "airdrop_calculate", label: "Airdrop" },
];
